name: Run Tests
on: [push, pull_request]
env:
  UV_PYTHON_DOWNLOADS: never
  UV_NO_DEV: 1
  PYTEST_ADDOPTS: "--color=yes"
jobs:
  tests:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          jack: jackd2
        - os: ubuntu-latest
          jack: jackd1
        # x86_64:
        - os: macos-15-intel
        # arm64:
        - os: macos-latest
        - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install JACK on Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends ${{ matrix.jack }}
    - name: Install JACK on macOS
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install jack
    - name: Install JACK on Windows
      if: startsWith(matrix.os, 'windows')
      # Inspired by https://github.com/supercollider/supercollider/blob/develop/.github/workflows/actions.yml
      shell: bash
      run: |
        JACK2_RELEASE=v1.9.22
        curl -O -J -L https://github.com/jackaudio/jack2-releases/releases/download/$JACK2_RELEASE/jack2-win64-$JACK2_RELEASE.exe
        ./jack2-win64-$JACK2_RELEASE.exe //SILENT //SUPPRESSMSGBOXES
        echo "/c/Program Files/JACK2" >> $GITHUB_PATH
    - name: Start jackd with "dummy" backend
      # With "bash", this works even on Windows!
      shell: bash
      run: |
        jackd --no-realtime -d dummy &
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
    - name: Install (editable) Python package
      run: |
        uv run --locked jack_build.py
    - name: Run tests
      run: |
        uv run --group test pytest

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Double-check Python version
      run: |
        python --version
    - name: Install doc dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --group doc
    - name: Create HTML docs
      run: |
        python -m sphinx -W --keep-going --color -d _build/doctrees doc _build/html -b html
    - name: Check for broken links
      run: |
        python -m sphinx -W --keep-going --color -d _build/doctrees doc _build/linkcheck -b linkcheck
